export enum CardFriendlyName {
    Cash1M,
    Cash2M,
    Cash3M,
    Cash4M,
    Cash5M,
    Cash10M,

    ActionDealBreaker,
    ActionJustSayNo,
    ActionPassGo,
    ActionForcedDeal,
    ActionSilyDeal,
    ActionDebtCollector,
    ActionItsMyBirthday,
    ActionDoubleTheRent,
    ActionHouse,
    ActionHotel,

    RentBlueAndGreen,
    RentRedAndYellow,
    RentPinkAndOrange,
    RentLightBlueAndBrown,
    RentRailroadAndUtility,
    RentWildRent,

    PropertyBlue,
    PropertyBrown,
    PropertyUtility,
    PropertyGreen,
    PropertyYellow,
    PropertyRed,
    PropertyOrange,
    PropertyPink,
    PropertyLightBlue,
    PropertyRailroad,

    PropertyWildCardBlueGreen,
    PropertyWildCardGreenRailroad,
    PropertyWildCardUtilityRailroad,
    PropertyWildCardLightBlueRailroad,
    PropertyWildCardLightBlueBrown,
    PropertyWildCardPinkOrange,
    PropertyWildCardRedYellow,
    PropertyWildCardMulticolor
}